--################
--## AUTOSTART ###
--################

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:

-- exec-once = $terminal
-- exec-once = nm-applet &
-- exec-once = ~/.config/waybar/scripts/launch.sh

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Notification daemon

--keyring daemon

hl.on("hyprland.start", function()
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("waybar")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("swaync")
    hl.exec_cmd("/usr/bin/gnome-keyring-daemon --start --components=secrets")
end)

