-- See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
    dwindle = {
        --    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
        preserve_split = true, -- You probably want this
    },
    -- See https://wiki.hypr.land/Configuring/Master-Layout/ for more
    master = {
        new_status = "master",
    },
})

