--###############
--## MONITORS ###
--###############

-- See https://wiki.hypr.land/Configuring/Monitors/
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@75.00",
    position = "0x0",
    scale = "1",
    cm = "srgb",
})

