--##################
--## MY PROGRAMS ###
--##################

-- See https://wiki.hypr.land/Configuring/Keywords/

-- Set programs that you use
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local terminal = "kitty"
local fileManager = "nautilus"
local menu = "wofi --show drun"

