-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- TODO: manual review — unknown section 'listener {' on line 8

-- TODO: manual review — unknown section 'listener {' on line 13
hl.config({
    general = {
        lock_cmd = "pidof hyprlock || hyprlock",
        before_sleep_cmd = "loginctl lock-session",
        after_sleep_cmd = "sleep 1 && hyprctl dispatch dpms on",
        ignore_dbus_inhibit = false,
    },
})

