-- This is an example Hyprland config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can split this configuration into multiple files
-- Create your files separately and then link them to this file like this:
-- source = ~/.config/hypr/myColors.conf

-- Sources
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: ~/.config/hypr/modules/monitors.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("modules.monitors")
-- Source: ~/.config/hypr/modules/programs.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("modules.programs")
-- Source: ~/.config/hypr/modules/autostart.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("modules.autostart")
-- Source: ~/.config/hypr/modules/env.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("modules.env")
-- Source: ~/.config/hypr/modules/permission.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("modules.permission")
-- Source: ~/.config/hypr/modules/decorations.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("modules.decorations")
-- Source: ~/.config/hypr/modules/animations.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("modules.animations")
-- Source: ~/.config/hypr/modules/windowrules.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("modules.windowrules")
-- Source: ~/.config/hypr/modules/layout.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("modules.layout")
-- Source: ~/.config/hypr/modules/misc.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("modules.misc")
-- Source: ~/.config/hypr/modules/input.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("modules.input")
-- Source: ~/.config/hypr/modules/keybindings.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("modules.keybindings")

hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
end)

