-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- TODO: manual review — unknown section 'background {' on line 1

-- TODO: manual review — unknown section 'input-field {' on line 17

-- TODO: manual review — unknown section 'label {' on line 38

-- TODO: manual review — unknown section 'label {' on line 49

-- TODO: manual review — unknown section 'label {' on line 60
hl.config({
    general = {
        ignore_empty_input = true,
        hide_cursor = false,
    },
})

