background {
    monitor =
    path = /home/walarch/Pictures/Wallpapers/wgruv_1.jpg
    blur_passes = 2
    blur_size = 7
    contrast = 0.9
    brightness = 0.75
    vibrancy = 0.15
    vibrancy_darkness = 0.1
}

general {
    ignore_empty_input = true
    hide_cursor = false
}

input-field {
    monitor =
    size = 220, 42
    outline_thickness = 1
    dots_size = 0.2
    dots_spacing = 0.25
    dots_center = true
    outer_color = rgb(60, 56, 54)         # #3c3836
    inner_color = rgb(40, 40, 40)         # #282828
    font_color = rgb(235, 219, 178)       # #ebdbb2
    fade_on_empty = true
    rounding = 8
    check_color = rgb(215, 153, 33)       # #d79921
    fail_color = rgb(251, 73, 52)         # #fb4934
    placeholder_text = <i>Enter Password...</i>
    font_family = JetBrainsMono Nerd Font Propo
    position = 0, -40
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgb(235, 219, 178)
    font_size = 90
    font_family = JetBrainsMono Nerd Font Propo
    position = 0, 140
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date +"%A, %B %d")"
    color = rgb(215, 153, 33)
    font_size = 18
    font_family = JetBrainsMono Nerd Font Propo
    position = 0, 60
    halign = center
    valign = center
}

label {
    monitor =
    text = Hi there, $USER
    color = rgb(168, 153, 132)
    font_size = 14
    font_family = JetBrainsMono Nerd Font Propo
    position = 0, -100
    halign = center
    valign = center
}
